import { colors } from "../../theme";

export const COURSES_DATA = {
  1: {
    id: 1,
    slug: "human-resources-management",
    title: "Human Resources Management",
    short: "HRM",
    level: "Intermediate",
    price: "₦45,000",
    priceNum: 45000,
    dur: "6 Weeks",
    students: "1,240",
    rating: 4.9,
    reviewCount: 187,
    color: "#F97316",
    bg: "linear-gradient(135deg,#FEF3C7,#FED7AA)",
    category: "Management",
    tagline: "Lead people, drive performance, transform organisations.",
    overview: `Human Resources Management is the backbone of every successful organisation. This programme equips you with the tools, frameworks and confidence to manage talent effectively — from attracting top candidates to building high-performing teams and navigating complex employee relations.

You will gain hands-on skills in recruitment strategy, compensation design, labour law compliance, performance management, and HR analytics. Whether you are stepping into HR for the first time or looking to formalise your experience with a recognised qualification, this course delivers real-world value from week one.`,
    outcomes: [
      "Design and execute end-to-end recruitment processes",
      "Build performance appraisal systems that actually work",
      "Navigate Nigerian labour law and international HR standards",
      "Apply HR analytics to support data-driven decisions",
      "Develop compensation, benefits and retention strategies",
      "Lead organisational change and workforce planning",
    ],
    curriculum: [
      {
        week: "Week 1–2",
        title: "Foundations of HRM",
        lessons: [
          "History & evolution of HR",
          "HR as a strategic partner",
          "Organisational structures & HR's role",
          "HR planning & workforce forecasting",
        ],
      },
      {
        week: "Week 3",
        title: "Talent Acquisition",
        lessons: [
          "Job analysis & description writing",
          "Sourcing strategies & employer branding",
          "Interview frameworks & candidate assessment",
          "Onboarding best practices",
        ],
      },
      {
        week: "Week 4",
        title: "Performance & Development",
        lessons: [
          "KPI setting & OKR frameworks",
          "Performance review cycles",
          "Coaching, mentoring & feedback models",
          "Training needs analysis",
        ],
      },
      {
        week: "Week 5",
        title: "Compensation & Employee Relations",
        lessons: [
          "Salary structuring & grading",
          "Benefits design & total reward",
          "Conflict resolution & disciplinary procedures",
          "Nigerian Labour Act overview",
        ],
      },
      {
        week: "Week 6",
        title: "HR Analytics & Certification Prep",
        lessons: [
          "HR metrics & dashboards",
          "People data & decision making",
          "Mock assessments & exam strategy",
          "Certificate examination",
        ],
      },
    ],
    reviews: [
      {
        name: "Adaeze O.",
        role: "HR Officer, Lagos",
        rating: 5,
        text: "This course completely changed how I approach recruitment. The labour law module alone saved my company from a costly mistake. Highly recommend.",
        avatar: "AO",
        color: "#F97316",
      },
      {
        name: "Emeka N.",
        role: "People Manager, Abuja",
        rating: 5,
        text: "Structured, practical and genuinely useful. The instructor feedback was detailed and the community of learners kept me motivated throughout.",
        avatar: "EN",
        color: colors.accent.teal,
      },
      {
        name: "Blessing T.",
        role: "Admin Officer → HR Lead",
        rating: 4,
        text: "I transitioned from admin to HR within 3 months of completing this. The certificate opened doors I did not expect. Worth every naira.",
        avatar: "BT",
        color: colors.accent.purple,
      },
    ],
    ratingBreakdown: [
      { stars: 5, pct: 78 },
      { stars: 4, pct: 14 },
      { stars: 3, pct: 6 },
      { stars: 2, pct: 1 },
      { stars: 1, pct: 1 },
    ],
    instructor: {
      name: "Dr. Chukwudi Eze",
      title: "Head of Curriculum, ProLearn Academy",
      bio: "15+ years in HR leadership across banking, FMCG and tech sectors.",
    },
  },
  2: {
    id: 2,
    slug: "project-management-professional",
    title: "Project Management Professional",
    short: "PMP",
    level: "Advanced",
    price: "₦65,000",
    priceNum: 65000,
    dur: "8 Weeks",
    students: "2,100",
    rating: 4.8,
    reviewCount: 312,
    color: colors.primary.main,
    bg: "linear-gradient(135deg,#DBEAFE,#BFDBFE)",
    category: "Management",
    tagline: "Lead projects that deliver — on time, on budget, every time.",
    overview: `The Project Management Professional programme is designed for professionals who want to master the art and science of delivering complex projects successfully. Aligned with PMI standards and covering both traditional and agile methodologies, this course prepares you for real-world project leadership.

From stakeholder management to risk mitigation, you'll develop the frameworks and communication skills to lead cross-functional teams and drive results that matter to your organisation.`,
    outcomes: [
      "Apply waterfall, agile and hybrid project frameworks",
      "Build detailed project plans, WBS and Gantt charts",
      "Manage budgets, timelines and resource allocation",
      "Identify, assess and mitigate project risks",
      "Lead and motivate cross-functional teams",
      "Prepare for PMP certification examination",
    ],
    curriculum: [
      {
        week: "Week 1–2",
        title: "Project Management Foundations",
        lessons: [
          "PMBOK guide overview",
          "Project lifecycle & process groups",
          "Stakeholder identification & analysis",
          "Project charter development",
        ],
      },
      {
        week: "Week 3–4",
        title: "Planning & Scheduling",
        lessons: [
          "Work Breakdown Structure (WBS)",
          "Gantt charts & critical path method",
          "Resource planning & allocation",
          "Budget estimation & cost baseline",
        ],
      },
      {
        week: "Week 5",
        title: "Agile & Hybrid Methods",
        lessons: [
          "Scrum framework deep dive",
          "Kanban & lean principles",
          "Hybrid project delivery",
          "Agile metrics & velocity",
        ],
      },
      {
        week: "Week 6",
        title: "Risk & Quality Management",
        lessons: [
          "Risk register & response strategies",
          "Quality planning & control",
          "Issue management & escalation",
          "Change control processes",
        ],
      },
      {
        week: "Week 7–8",
        title: "Execution, Closure & Exam Prep",
        lessons: [
          "Project monitoring & reporting",
          "Stakeholder communication plans",
          "Project closure & lessons learned",
          "PMP mock examinations",
        ],
      },
    ],
    reviews: [
      {
        name: "Tunde A.",
        role: "Project Manager, MTN Nigeria",
        rating: 5,
        text: "The agile module was world-class. I passed my PMP exam on the first attempt and got a promotion within 2 months.",
        avatar: "TA",
        color: colors.primary.main,
      },
      {
        name: "Chisom I.",
        role: "IT Project Lead",
        rating: 5,
        text: "Best investment I have made in my career. The instructors are practitioners, not just academics — every example was relatable.",
        avatar: "CI",
        color: "#F97316",
      },
      {
        name: "Fatima B.",
        role: "Program Officer, NGO",
        rating: 4,
        text: "Very comprehensive. The risk management section helped me immediately on my current project. Excellent value.",
        avatar: "FB",
        color: colors.accent.green,
      },
    ],
    ratingBreakdown: [
      { stars: 5, pct: 74 },
      { stars: 4, pct: 18 },
      { stars: 3, pct: 6 },
      { stars: 2, pct: 1 },
      { stars: 1, pct: 1 },
    ],
    instructor: {
      name: "Dr. Amina Okafor",
      title: "Founder & CEO, ProLearn Academy",
      bio: "PMP-certified with 18 years managing projects across finance, construction and technology sectors.",
    },
  },
  3: {
    id: 3,
    slug: "health-safety-environment-i",
    title: "Health Safety & Environment I",
    short: "HSE I",
    level: "Beginner",
    price: "₦35,000",
    priceNum: 35000,
    dur: "4 Weeks",
    students: "980",
    rating: 4.7,
    reviewCount: 143,
    color: colors.accent.green,
    bg: "linear-gradient(135deg,#DCFCE7,#BBF7D0)",
    category: "Safety",
    tagline: "Build the safety foundation every workplace depends on.",
    overview: `HSE Level I is the entry point for professionals entering the health, safety and environment field. This foundational programme covers the essential principles of workplace safety, hazard identification, risk assessment and regulatory compliance.

Whether you work in oil & gas, construction, manufacturing or any other sector, this certification demonstrates your commitment to creating safe, compliant and sustainable work environments.`,
    outcomes: [
      "Identify and classify workplace hazards",
      "Conduct basic risk assessments",
      "Understand OSHA and Nigerian safety regulations",
      "Respond to workplace incidents and emergencies",
      "Complete safety documentation and reporting",
      "Promote a safety-first culture within your team",
    ],
    curriculum: [
      {
        week: "Week 1",
        title: "Introduction to HSE",
        lessons: [
          "History of workplace safety",
          "Key HSE legislation in Nigeria",
          "Roles & responsibilities of HSE officers",
          "Safety management systems overview",
        ],
      },
      {
        week: "Week 2",
        title: "Hazard Identification & Risk Assessment",
        lessons: [
          "Types of workplace hazards",
          "HAZOP & HAZID methods",
          "Risk matrix & scoring",
          "Control hierarchy (ERICPD)",
        ],
      },
      {
        week: "Week 3",
        title: "Emergency Preparedness",
        lessons: [
          "Emergency response planning",
          "Fire safety & evacuation procedures",
          "First aid principles",
          "Incident reporting & investigation basics",
        ],
      },
      {
        week: "Week 4",
        title: "Compliance & Certification Prep",
        lessons: [
          "PPE selection & usage",
          "Safety audits & inspections",
          "HSE documentation",
          "Certification examination",
        ],
      },
    ],
    reviews: [
      {
        name: "Uche M.",
        role: "Site Supervisor, Construction",
        rating: 5,
        text: "I went from zero knowledge to confidently running site safety briefings. This course is practical and easy to follow.",
        avatar: "UM",
        color: colors.accent.green,
      },
      {
        name: "Grace A.",
        role: "HSE Officer, Oil & Gas",
        rating: 4,
        text: "Good foundation. The risk assessment framework is exactly what I needed to pass my employer's internal HSE audit.",
        avatar: "GA",
        color: "#F97316",
      },
      {
        name: "Ibrahim S.",
        role: "Factory Floor Manager",
        rating: 5,
        text: "Clear, well-paced and highly relevant to the Nigerian workplace. The instructors understood local context perfectly.",
        avatar: "IS",
        color: colors.accent.teal,
      },
    ],
    ratingBreakdown: [
      { stars: 5, pct: 70 },
      { stars: 4, pct: 20 },
      { stars: 3, pct: 8 },
      { stars: 2, pct: 1 },
      { stars: 1, pct: 1 },
    ],
    instructor: {
      name: "James Adeyemi",
      title: "Lead Instructor, HSE — ProLearn Academy",
      bio: "Certified HSE professional with 12 years in oil & gas, construction and manufacturing sectors across West Africa.",
    },
  },
};

// Generate remaining courses from base data
const BASE = [
  {
    id: 4,
    slug: "health-safety-environment-ii",
    title: "Health Safety & Environment II",
    short: "HSE II",
    level: "Intermediate",
    price: "₦40,000",
    priceNum: 40000,
    dur: "5 Weeks",
    students: "740",
    rating: 4.8,
    reviewCount: 98,
    color: colors.accent.green,
    bg: "linear-gradient(135deg,#DCFCE7,#D1FAE5)",
    category: "Safety",
    tagline:
      "Advance your HSE skills and take on greater workplace responsibility.",
  },
  {
    id: 5,
    slug: "health-safety-environment-iii",
    title: "Health Safety & Environment III",
    short: "HSE III",
    level: "Advanced",
    price: "₦50,000",
    priceNum: 50000,
    dur: "6 Weeks",
    students: "520",
    rating: 4.7,
    reviewCount: 76,
    color: colors.accent.green,
    bg: "linear-gradient(135deg,#A7F3D0,#BBF7D0)",
    category: "Safety",
    tagline: "Master senior-level HSE management, auditing and compliance.",
  },
  {
    id: 6,
    slug: "customer-relations-management",
    title: "Customer Relations Management",
    short: "CRM",
    level: "Intermediate",
    price: "₦38,000",
    priceNum: 38000,
    dur: "4 Weeks",
    students: "760",
    rating: 4.8,
    reviewCount: 121,
    color: colors.accent.teal,
    bg: "linear-gradient(135deg,#E0F2FE,#BAE6FD)",
    category: "Business",
    tagline:
      "Build exceptional customer experiences that drive loyalty and revenue.",
  },
  {
    id: 7,
    slug: "business-management-professional",
    title: "Business Management Professional",
    short: "BMP",
    level: "Advanced",
    price: "₦75,000",
    priceNum: 75000,
    dur: "10 Weeks",
    students: "1,540",
    rating: 4.9,
    reviewCount: 234,
    color: colors.accent.purple,
    bg: "linear-gradient(135deg,#F3E8FF,#DDD6FE)",
    category: "Management",
    tagline: "Master end-to-end business strategy, operations and leadership.",
  },
  {
    id: 8,
    slug: "entrepreneurship-management",
    title: "Entrepreneurship Management",
    short: "EMP",
    level: "Intermediate",
    price: "₦42,000",
    priceNum: 42000,
    dur: "6 Weeks",
    students: "890",
    rating: 4.8,
    reviewCount: 156,
    color: "#F97316",
    bg: "linear-gradient(135deg,#FEF9C3,#FEF08A)",
    category: "Business",
    tagline: "Launch, grow and scale your own business with confidence.",
  },
  {
    id: 9,
    slug: "dhis2-health-informatics",
    title: "DHIS2 & Health Informatics",
    short: "DHI",
    level: "Intermediate",
    price: "₦40,000",
    priceNum: 40000,
    dur: "5 Weeks",
    students: "430",
    rating: 4.6,
    reviewCount: 67,
    color: colors.accent.teal,
    bg: "linear-gradient(135deg,#CFFAFE,#A5F3FC)",
    category: "Technology",
    tagline: "Master DHIS2 data systems and drive smarter health decisions.",
  },
  {
    id: 10,
    slug: "information-security-management",
    title: "Information Security Management",
    short: "ISM",
    level: "Advanced",
    price: "₦60,000",
    priceNum: 60000,
    dur: "7 Weeks",
    students: "890",
    rating: 4.8,
    reviewCount: 142,
    color: "#334155",
    bg: "linear-gradient(135deg,#F1F5F9,#E2E8F0)",
    category: "Technology",
    tagline:
      "Protect organisations from cyber threats with proven security frameworks.",
  },
];

BASE.forEach((b) => {
  if (!COURSES_DATA[b.id]) {
    COURSES_DATA[b.id] = {
      ...b,
      overview: `${b.title} is a professionally designed programme built for ambitious professionals in ${b.category.toLowerCase()}. This course delivers practical, industry-relevant knowledge and skills that you can apply immediately in your workplace, backed by a globally recognised ProLearn Academy certificate.`,
      outcomes: [
        `Master core concepts and frameworks in ${b.category.toLowerCase()}`,
        "Apply practical skills directly in your current role",
        "Complete real-world assessments and case studies",
        "Earn an internationally recognised ProLearn certificate",
        "Join a network of 12,000+ certified professionals",
        "Access lifetime course materials and updates",
      ],
      curriculum: [
        {
          week: "Week 1–2",
          title: "Foundations & Core Concepts",
          lessons: [
            "Programme introduction & objectives",
            "Industry overview & career pathways",
            "Key frameworks and methodologies",
            "Assessment overview",
          ],
        },
        {
          week: "Week 3–4",
          title: "Core Skills Development",
          lessons: [
            "Hands-on practical exercises",
            "Case studies & real-world scenarios",
            "Peer learning & group work",
            "Mid-programme assessment",
          ],
        },
        {
          week: "Week 5+",
          title: "Advanced Application & Certification",
          lessons: [
            "Advanced topics & specialisations",
            "Industry tools and software",
            "Final project & portfolio",
            "Certificate examination",
          ],
        },
      ],
      reviews: [
        {
          name: "Oluwaseun A.",
          role: `${b.category} Professional, Lagos`,
          rating: 5,
          text: "Outstanding programme. Practical, relevant and delivered by genuine experts. My career has moved forward significantly since completing this.",
          avatar: "OA",
          color: b.color === "#334155" ? colors.primary.main : b.color,
        },
        {
          name: "Ngozi C.",
          role: "Recent Graduate",
          rating: 4,
          text: "Very well structured. The assessments pushed me to truly understand the material. I feel confident applying these skills now.",
          avatar: "NC",
          color: "#F97316",
        },
        {
          name: "Damilola F.",
          role: "Team Lead, Abuja",
          rating: 5,
          text: "Worth every naira. The certificate is recognised and the quality of instruction is excellent. Highly recommend to anyone serious about their career.",
          avatar: "DF",
          color: colors.accent.teal,
        },
      ],
      ratingBreakdown: [
        { stars: 5, pct: 72 },
        { stars: 4, pct: 18 },
        { stars: 3, pct: 7 },
        { stars: 2, pct: 2 },
        { stars: 1, pct: 1 },
      ],
      instructor: {
        name: "Dr. Amina Okafor",
        title: "Founder & CEO, ProLearn Academy",
        bio: "18 years of industry experience across multiple sectors with a passion for accessible professional education.",
      },
    };
  }
});

export default COURSES_DATA;

/* ── slug → id map ── */
export const SLUG_MAP = {
  "human-resources-management": 1,
  "project-management-professional": 2,
  "health-safety-environment-i": 3,
  "health-safety-environment-ii": 4,
  "health-safety-environment-iii": 5,
  "customer-relations-management": 6,
  "business-management-professional": 7,
  "entrepreneurship-management": 8,
  "dhis2-health-informatics": 9,
  "information-security-management": 10,
};
